name: controle_saudavel
description: App de controle alimentar e saÃºde com reconhecimento de imagem.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.1.2
  fl_chart: ^0.69.0
  google_sign_in: ^7.2.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/pt-BR.json
    - assets/i18n/en-US.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
